### PR TITLE
Adds a flag to the admins collection called isMaintenanceUser

### PR DESCRIPTION
**Pull request by Princesso**
**What this PR does:**

- Adds an isMaintenanceUser type  to the admin collection
- Displays the maintenance user check on the admin list
- Updates data from the database to have an isMaintenanceUser object

**Link to story**
https://wellbeyondwater.monday.com/boards/1075561183/pulses/1077235096

**Images or video showing the feature**

https://user-images.githubusercontent.com/13929923/109202318-22abef80-77a3-11eb-89eb-4a126412276f.mp4

**Checklists**
- [ ✓] Tests written?
- [ ✓] Tests passing?

### CODE REVIEW

**Review by daveh957 — CHANGES_REQUESTED** [review]
My fault for not being clearer on this.  The list of organizations is only relevant if the 'isClientAdmin' flag is true.  For either a system administrator or a user who can do just do the maintenance function the list or organizations should be blank and disabled.

**Comment by Princesso** [comment]
> My fault for not being clearer on this. The list of organizations is only relevant if the 'isClientAdmin' flag is true. For either a system administrator or a user who can do just do the maintenance function the list or organizations should be blank and disabled.

Fixed, please have another look. Thanks.

**Review by daveh957 — APPROVED** [review]
Just make this one change to AdminType.tsx to clear out the organizations for maintenance users, and we are good to go.

`         if(choice !== 'isClientAdmin') form.change('organizations',[])`

**Comment by daveh957** [comment]
After you merge go ahead and deploy it.  [https://github.com/WellBeyond/wellbeyond-admin/blob/master/docs/building.md](https://github.com/WellBeyond/wellbeyond-admin/blob/master/docs/building.md)

**Pull request merged**
